/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyThehotel360RouteImport } from './routes/why-thehotel360'
import { Route as SettlementRouteImport } from './routes/settlement'
import { Route as ReservationFrontOfficeRouteImport } from './routes/reservation-front-office'
import { Route as RequestDemoRouteImport } from './routes/request-demo'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnlineBookingRouteImport } from './routes/online-booking'
import { Route as NightAuditRouteImport } from './routes/night-audit'
import { Route as MultiPropertyRouteImport } from './routes/multi-property'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as HrmPayrollRouteImport } from './routes/hrm-payroll'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CashDrawerRouteImport } from './routes/cash-drawer'
import { Route as AccountingFinanceRouteImport } from './routes/accounting-finance'
import { Route as IndexRouteImport } from './routes/index'

const WhyThehotel360Route = WhyThehotel360RouteImport.update({
  id: '/why-thehotel360',
  path: '/why-thehotel360',
  getParentRoute: () => rootRouteImport,
} as any)
const SettlementRoute = SettlementRouteImport.update({
  id: '/settlement',
  path: '/settlement',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationFrontOfficeRoute = ReservationFrontOfficeRouteImport.update({
  id: '/reservation-front-office',
  path: '/reservation-front-office',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestDemoRoute = RequestDemoRouteImport.update({
  id: '/request-demo',
  path: '/request-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineBookingRoute = OnlineBookingRouteImport.update({
  id: '/online-booking',
  path: '/online-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const NightAuditRoute = NightAuditRouteImport.update({
  id: '/night-audit',
  path: '/night-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiPropertyRoute = MultiPropertyRouteImport.update({
  id: '/multi-property',
  path: '/multi-property',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const HrmPayrollRoute = HrmPayrollRouteImport.update({
  id: '/hrm-payroll',
  path: '/hrm-payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CashDrawerRoute = CashDrawerRouteImport.update({
  id: '/cash-drawer',
  path: '/cash-drawer',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingFinanceRoute = AccountingFinanceRouteImport.update({
  id: '/accounting-finance',
  path: '/accounting-finance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounting-finance': typeof AccountingFinanceRoute
  '/cash-drawer': typeof CashDrawerRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/hrm-payroll': typeof HrmPayrollRoute
  '/inventory': typeof InventoryRoute
  '/modules': typeof ModulesRoute
  '/multi-property': typeof MultiPropertyRoute
  '/night-audit': typeof NightAuditRoute
  '/online-booking': typeof OnlineBookingRoute
  '/pricing': typeof PricingRoute
  '/reports': typeof ReportsRoute
  '/request-demo': typeof RequestDemoRoute
  '/reservation-front-office': typeof ReservationFrontOfficeRoute
  '/settlement': typeof SettlementRoute
  '/why-thehotel360': typeof WhyThehotel360Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounting-finance': typeof AccountingFinanceRoute
  '/cash-drawer': typeof CashDrawerRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/hrm-payroll': typeof HrmPayrollRoute
  '/inventory': typeof InventoryRoute
  '/modules': typeof ModulesRoute
  '/multi-property': typeof MultiPropertyRoute
  '/night-audit': typeof NightAuditRoute
  '/online-booking': typeof OnlineBookingRoute
  '/pricing': typeof PricingRoute
  '/reports': typeof ReportsRoute
  '/request-demo': typeof RequestDemoRoute
  '/reservation-front-office': typeof ReservationFrontOfficeRoute
  '/settlement': typeof SettlementRoute
  '/why-thehotel360': typeof WhyThehotel360Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounting-finance': typeof AccountingFinanceRoute
  '/cash-drawer': typeof CashDrawerRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/hrm-payroll': typeof HrmPayrollRoute
  '/inventory': typeof InventoryRoute
  '/modules': typeof ModulesRoute
  '/multi-property': typeof MultiPropertyRoute
  '/night-audit': typeof NightAuditRoute
  '/online-booking': typeof OnlineBookingRoute
  '/pricing': typeof PricingRoute
  '/reports': typeof ReportsRoute
  '/request-demo': typeof RequestDemoRoute
  '/reservation-front-office': typeof ReservationFrontOfficeRoute
  '/settlement': typeof SettlementRoute
  '/why-thehotel360': typeof WhyThehotel360Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounting-finance'
    | '/cash-drawer'
    | '/contact'
    | '/features'
    | '/hrm-payroll'
    | '/inventory'
    | '/modules'
    | '/multi-property'
    | '/night-audit'
    | '/online-booking'
    | '/pricing'
    | '/reports'
    | '/request-demo'
    | '/reservation-front-office'
    | '/settlement'
    | '/why-thehotel360'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounting-finance'
    | '/cash-drawer'
    | '/contact'
    | '/features'
    | '/hrm-payroll'
    | '/inventory'
    | '/modules'
    | '/multi-property'
    | '/night-audit'
    | '/online-booking'
    | '/pricing'
    | '/reports'
    | '/request-demo'
    | '/reservation-front-office'
    | '/settlement'
    | '/why-thehotel360'
  id:
    | '__root__'
    | '/'
    | '/accounting-finance'
    | '/cash-drawer'
    | '/contact'
    | '/features'
    | '/hrm-payroll'
    | '/inventory'
    | '/modules'
    | '/multi-property'
    | '/night-audit'
    | '/online-booking'
    | '/pricing'
    | '/reports'
    | '/request-demo'
    | '/reservation-front-office'
    | '/settlement'
    | '/why-thehotel360'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountingFinanceRoute: typeof AccountingFinanceRoute
  CashDrawerRoute: typeof CashDrawerRoute
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  HrmPayrollRoute: typeof HrmPayrollRoute
  InventoryRoute: typeof InventoryRoute
  ModulesRoute: typeof ModulesRoute
  MultiPropertyRoute: typeof MultiPropertyRoute
  NightAuditRoute: typeof NightAuditRoute
  OnlineBookingRoute: typeof OnlineBookingRoute
  PricingRoute: typeof PricingRoute
  ReportsRoute: typeof ReportsRoute
  RequestDemoRoute: typeof RequestDemoRoute
  ReservationFrontOfficeRoute: typeof ReservationFrontOfficeRoute
  SettlementRoute: typeof SettlementRoute
  WhyThehotel360Route: typeof WhyThehotel360Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-thehotel360': {
      id: '/why-thehotel360'
      path: '/why-thehotel360'
      fullPath: '/why-thehotel360'
      preLoaderRoute: typeof WhyThehotel360RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settlement': {
      id: '/settlement'
      path: '/settlement'
      fullPath: '/settlement'
      preLoaderRoute: typeof SettlementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation-front-office': {
      id: '/reservation-front-office'
      path: '/reservation-front-office'
      fullPath: '/reservation-front-office'
      preLoaderRoute: typeof ReservationFrontOfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-demo': {
      id: '/request-demo'
      path: '/request-demo'
      fullPath: '/request-demo'
      preLoaderRoute: typeof RequestDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-booking': {
      id: '/online-booking'
      path: '/online-booking'
      fullPath: '/online-booking'
      preLoaderRoute: typeof OnlineBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/night-audit': {
      id: '/night-audit'
      path: '/night-audit'
      fullPath: '/night-audit'
      preLoaderRoute: typeof NightAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multi-property': {
      id: '/multi-property'
      path: '/multi-property'
      fullPath: '/multi-property'
      preLoaderRoute: typeof MultiPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hrm-payroll': {
      id: '/hrm-payroll'
      path: '/hrm-payroll'
      fullPath: '/hrm-payroll'
      preLoaderRoute: typeof HrmPayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-drawer': {
      id: '/cash-drawer'
      path: '/cash-drawer'
      fullPath: '/cash-drawer'
      preLoaderRoute: typeof CashDrawerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting-finance': {
      id: '/accounting-finance'
      path: '/accounting-finance'
      fullPath: '/accounting-finance'
      preLoaderRoute: typeof AccountingFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountingFinanceRoute: AccountingFinanceRoute,
  CashDrawerRoute: CashDrawerRoute,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  HrmPayrollRoute: HrmPayrollRoute,
  InventoryRoute: InventoryRoute,
  ModulesRoute: ModulesRoute,
  MultiPropertyRoute: MultiPropertyRoute,
  NightAuditRoute: NightAuditRoute,
  OnlineBookingRoute: OnlineBookingRoute,
  PricingRoute: PricingRoute,
  ReportsRoute: ReportsRoute,
  RequestDemoRoute: RequestDemoRoute,
  ReservationFrontOfficeRoute: ReservationFrontOfficeRoute,
  SettlementRoute: SettlementRoute,
  WhyThehotel360Route: WhyThehotel360Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
